name: flyweight_code
dependencies:
  reflectable: any
dependency_overrides:
  analyzer: '0.26.1+14'
transformers:
- reflectable:
    entry_points:
      - bin/coffee_orders.dart
    formatted: true
# - $dart2js:
#     $include: []
